### model
model_name_or_path: /home/user/xiexiurui/pgw/NLG/pre_model/Llama-3.2-1B

### method
stage: pt
do_train: true
finetuning_type: snndlft
lora_target: q_proj,v_proj
target_r: 1
init_r: 2
deltaT: 1
tfinal: 10
tinit: 5
lora_alpha: 32
layer_wise: single


### dataset
dataset: wiki_demo
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/wiki_demo/snndlft
logging_steps: 10
save_steps: 10
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
save_safetensors: false

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
