
### model
model_name_or_path: Qwen/Qwen2.5-0.5B

### initial
ratio: 0.25
rank: 64
save_dir: model_zoo/eqft/

### method
stage: pt
do_train: true
finetuning_type: meqft
lora_target: q_proj, v_proj

### dataset
dataset: c4_demo
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen/eqft/wiki
logging_steps: 10
save_steps: 20
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
save_safetensors: false

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
